---

- hosts: 192.168.182.118

  tasks:
  - name: Installation du serveur Apache et PHP
    yum:
     name: "{{ item }}"
     state: present
    loop:
      - httpd
      - php
      - nano
      - mariadb-server

  - name: Arret du service nginx
    systemd:
     name: nginx
     state: stopped

  - name: Démarrage du serveur apache
    systemd:
     name: "{{ item }}"
     state: started
    loop:
      - httpd
      - mariadb
